version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: my_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    ports:
      - "8000:8000"
    container_name: my_python_app
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
    depends_on:
      - mongodb

volumes:
  mongo_data: